#!/bin/sh

failed=false
if [ "$(git config --list --local | grep user.name)" = "" ]
then
  echo 'Error: user.name not specified'
  failed=true
fi

if [ "$(git config --list --local | grep user.email)" = "" ]
then
  echo 'Error: user.email not specified'
  failed=true
fi

if [ "$(git config --list --local | grep core.autocrlf)" = "" ]
then
  echo 'Error: core.autocrlf not specified'
  failed=true
fi

if [ "$failed" = true ]
then
  echo ""
  echo "RRRRRR  EEEEEEE     JJJ EEEEEEE  CCCCC TTTTTTT EEEEEEE DDDDD"
  echo "RR   RR EE          JJJ EE      CC       TTT   EE      DD  DD"
  echo "RRRRRR  EEEEE       JJJ EEEEE   CC       TTT   EEEEE   DD   DD"
  echo "RR  RR  EE      JJ  JJJ EE      CC       TTT   EE      DD  DD"
  echo "RR   RR EEEEEEE  JJJJJ  EEEEEEE  CCCCC   TTT   EEEEEEE DDDDD"
  echo ""
  exit 1
fi
